# Generated by Django 4.0.6 on 2022-07-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(blank=True, max_length=10, null=True)),
                ('job', models.CharField(blank=True, max_length=9, null=True)),
                ('mgr', models.IntegerField(blank=True, null=True)),
                ('hiredate', models.DateField(blank=True, null=True)),
                ('sal', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('comm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('deptno', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emp',
                'managed': False,
            },
        ),
    ]
